[project]
name = "dyrmgraph-libs"
version = "0.1.0"

[project.optional-dependencies]
test = [
    "pytest", "pytest-cov", 
    "pytest-asyncio", "mock", 
    "dbt-core", "dbt-spark",
    "aiohttp", "aiofiles", "minio"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["libs*", "services*"]

[tool.ruff]
line-length = 120