package com.dyrmgraph.transform;

import org.apache.spark.sql.types.StructType;

import java.util.Map;

public final class Schema {

    private static final StructType GKG_SCHEMA = new StructType()
            .add("GKGRecordID", "string")
            .add("V2_1Date", "string")
            .add("V2SourceCollectionIdentifier", "string")
            .add("V2SourceCommonName", "string")
            .add("V2DocumentIdentifier", "string")
            .add("V1Counts", "string")
            .add("V2_1Counts", "string")
            .add("V1Themes", "string")
            .add("V2EnhancedThemes", "string")
            .add("V1Locations", "string")
            .add("V2EnhancedLocations", "string")
            .add("V1Persons", "string")
            .add("V2EnhancedPersons", "string")
            .add("V1Organizations", "string")
            .add("V2EnhancedOrganizations", "string")
            .add("V1_5Tone", "string")
            .add("V2_1EnhancedDates", "string")
            .add("V2GCAM", "string")
            .add("V2_1SharingImage", "string")
            .add("V2_1RelatedImages", "string")
            .add("V2_1SocialImageEmbeds", "string")
            .add("V2_1SocialVideoEmbeds", "string")
            .add("V2_1Quotations", "string")
            .add("V2_1AllNames", "string")
            .add("V2_1Amounts", "string")
            .add("V2_1TranslationInfo", "string")
            .add("V2ExtraSXML", "string");

    private static final StructType EVENTS_SCHEMA = new StructType()
            .add("GlobalEventID", "string")
            .add("Day", "string")
            .add("MonthYear", "string")
            .add("Year", "string")
            .add("FractionDate", "string")
            .add("Actor1Code", "string")
            .add("Actor1Name", "string")
            .add("Actor1CountryCode", "string")
            .add("Actor1KnownGroupCode", "string")
            .add("Actor1EthnicCode", "string")
            .add("Actor1Religion1Code", "string")
            .add("Actor1Religion2Code", "string")
            .add("Actor1Type1Code", "string")
            .add("Actor1Type2Code", "string")
            .add("Actor1Type3Code", "string")
            .add("Actor2Code", "string")
            .add("Actor2Name", "string")
            .add("Actor2CountryCode", "string")
            .add("Actor2KnownGroupCode", "string")
            .add("Actor2EthnicCode", "string")
            .add("Actor2Religion1Code", "string")
            .add("Actor2Religion2Code", "string")
            .add("Actor2Type1Code", "string")
            .add("Actor2Type2Code", "string")
            .add("Actor2Type3Code", "string")
            .add("IsRootEvent", "string")
            .add("EventCode", "string")
            .add("EventBaseCode", "string")
            .add("EventRootCode", "string")
            .add("QuadClass", "string")
            .add("GoldsteinScale", "string")
            .add("NumMentions", "string")
            .add("NumSources", "string")
            .add("NumArticles", "string")
            .add("AvgTone", "string")
            .add("Actor1GeoType", "string")
            .add("Actor1GeoFullName", "string")
            .add("Actor1GeoCountryCode", "string")
            .add("Actor1GeoADM1Code", "string")
            .add("Actor1GeoADM2Code", "string")
            .add("Actor1GeoLat", "string")
            .add("Actor1GeoLong", "string")
            .add("Actor1GeoFeatureID", "string")
            .add("Actor2GeoType", "string")
            .add("Actor2GeoFullName", "string")
            .add("Actor2GeoCountryCode", "string")
            .add("Actor2GeoADM1Code", "string")
            .add("Actor2GeoADM2Code", "string")
            .add("Actor2GeoLat", "string")
            .add("Actor2GeoLong", "string")
            .add("Actor2GeoFeatureID", "string")
            .add("ActionGeoType", "string")
            .add("ActionGeoFullName", "string")
            .add("ActionGeoCountryCode", "string")
            .add("ActionGeoADM1Code", "string")
            .add("ActionGeoADM2Code", "string")
            .add("ActionGeoLat", "string")
            .add("ActionGeoLong", "string")
            .add("ActionGeoFeatureID", "string")
            .add("DateAdded", "string")
            .add("SourceURL", "string");

    private static final StructType MENTIONS_SCHEMA = new StructType()
            .add("GlobalEventID", "string")
            .add("EventTimeDate", "string")
            .add("MentionTimeDate", "string")
            .add("MentionType", "string")
            .add("MentionSourceName", "string")
            .add("MentionIdentifier", "string")
            .add("SentenceID", "string")
            .add("Actor1CharOffset", "string")
            .add("Actor2CharOffset", "string")
            .add("ActionCharOffset", "string")
            .add("InRawText", "string")
            .add("Confidence", "string")
            .add("MentionDocLen", "string")
            .add("MentionDocTone", "string")
            .add("MentionDocTranslationInfo", "string")
            .add("Extras", "string");

    public static Map<String, StructType> schemaMap = Map.of(
            "gkg", GKG_SCHEMA,
            "events", EVENTS_SCHEMA,
            "mentions", MENTIONS_SCHEMA);

    private Schema() {
    }
}
