dyrmgraph:
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-iceberg
      port: 10000
      schema: transformation

      threads: 1
      connect_retries: 20
      connect_timeout: 10
      retry_all: true

      user: root
      auth: NONE
      use_ssl: false
  target: dev
